/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddNewElementButton {
        "activeFunction": (input:string|boolean) => void;
        "buttonName": string;
        "inputFunctionOne": string|boolean;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface NodeComponent {
        "inputClick": () => void;
        "inputs": string[];
        "nodeId": string;
        "output": string;
        "outputClick": () => void;
    }
    interface NodeEditorComponent {
        "addReturnode": () => Promise<void>;
    }
    interface NodeElement {
    }
}
declare global {
    interface HTMLAddNewElementButtonElement extends Components.AddNewElementButton, HTMLStencilElement {
    }
    var HTMLAddNewElementButtonElement: {
        prototype: HTMLAddNewElementButtonElement;
        new (): HTMLAddNewElementButtonElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLNodeComponentElement extends Components.NodeComponent, HTMLStencilElement {
    }
    var HTMLNodeComponentElement: {
        prototype: HTMLNodeComponentElement;
        new (): HTMLNodeComponentElement;
    };
    interface HTMLNodeEditorComponentElement extends Components.NodeEditorComponent, HTMLStencilElement {
    }
    var HTMLNodeEditorComponentElement: {
        prototype: HTMLNodeEditorComponentElement;
        new (): HTMLNodeEditorComponentElement;
    };
    interface HTMLNodeElementElement extends Components.NodeElement, HTMLStencilElement {
    }
    var HTMLNodeElementElement: {
        prototype: HTMLNodeElementElement;
        new (): HTMLNodeElementElement;
    };
    interface HTMLElementTagNameMap {
        "add-new-element-button": HTMLAddNewElementButtonElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "node-component": HTMLNodeComponentElement;
        "node-editor-component": HTMLNodeEditorComponentElement;
        "node-element": HTMLNodeElementElement;
    }
}
declare namespace LocalJSX {
    interface AddNewElementButton {
        "activeFunction"?: (input:string|boolean) => void;
        "buttonName"?: string;
        "inputFunctionOne"?: string|boolean;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface NodeComponent {
        "inputClick"?: () => void;
        "inputs"?: string[];
        "nodeId"?: string;
        "output"?: string;
        "outputClick"?: () => void;
    }
    interface NodeEditorComponent {
    }
    interface NodeElement {
    }
    interface IntrinsicElements {
        "add-new-element-button": AddNewElementButton;
        "app-home": AppHome;
        "app-root": AppRoot;
        "node-component": NodeComponent;
        "node-editor-component": NodeEditorComponent;
        "node-element": NodeElement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-new-element-button": LocalJSX.AddNewElementButton & JSXBase.HTMLAttributes<HTMLAddNewElementButtonElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "node-component": LocalJSX.NodeComponent & JSXBase.HTMLAttributes<HTMLNodeComponentElement>;
            "node-editor-component": LocalJSX.NodeEditorComponent & JSXBase.HTMLAttributes<HTMLNodeEditorComponentElement>;
            "node-element": LocalJSX.NodeElement & JSXBase.HTMLAttributes<HTMLNodeElementElement>;
        }
    }
}
